apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-assistant
  namespace: aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiops-assistant
  template:
    metadata:
      labels:
        app: aiops-assistant
    spec:
      containers:
        - name: app
          image: aiops-assistant:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          envFrom:
            - secretRef:
                name: aiops-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
