apiVersion: v1
kind: Service
metadata:
  name: aiops-assistant
  namespace: aiops
spec:
  type: NodePort
  selector:
    app: aiops-assistant
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      nodePort: 30081
